### ISSUE TITLE
Every variant of cluBuildSource*() should have a compile_options parameter

### ISSUE THREAD

**Issue by noma** [Computing-Language-Utility/CLU#23]
Only cluBuildSourceArray() offers a compile_options parameter, which forces the user to manually read a .cl-file in case she wants to specify compiler options. To my experience, the latter is very common to pass defines for code configuration and compile-time arguments.

If whoever is responsible for that decision agrees, I would happily deliver the changes as a pull request.

**Comment by noma** [comment]
Just found clu_initialize_params::compile_options which seems to be the intended way of setting compile options - but why has cluBuildSourceArray an extra parameter then? 

Nevertheless, setting these options once at initialisation is insufficient for some use cases as described in the first comment. Another use case are performance studies of the same kernel with different options.

**Comment by Computing-Language-Utility** [comment]
Sure, I’d be happy to integrate!

**Comment by noma** [comment]
Here is a link to my fork, where I added an option parameter to all the build functions that did not already have one. While this seemed the cleanest solution, given the 'extern "C"'-constraints, it might break compatibility with existing code like the examples.

https://github.com/noma/CLU/compare/Computing-Language-Utility:master...master

Another option would be to add differently named variants of the functions, but this would be inconsistent with those functions that already have the compile_options parameter.

What do you think?

**Comment by Computing-Language-Utility** [comment]
I'm a little worried this makes the "very easy" API a little less easy. Maybe in this case it's justified?

Probably should integrate. Send a pull request?

**Comment by Computing-Language-Utility** [comment]
Ok, I tried to do this myself. Changed a few things internally to simplify. Hope I didn't break anything.

**Comment by noma** [comment]
Thanks for the effort. I've reviewed the commit and added a few notes 3c598c57fa884e830d37645cd93fc598220dce71

**Comment by noma** [comment]
I've tested the changes with my project and it works for me. Thanks!
